### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Blindingend** [Veiasai/Xmap#10]
# web 端

- [ ] 1. 优化界面
- [x] 2. 优化操作逻辑
- [x] 3. 优化登录验证
- [x] 4. 点位修改功能
- [ ] 5. 批量导出的界面和删除功能优化
- [ ] 6. 导出二维码的样式优化

# 小程序端

- [x] 2. 路线详细信息查看图片消失的 bug
- [x] 3. 路线制作时sroll-view 始终在最下面的优化
- [x] 4. 整体 UI 风格的调整
- [ ] 5. 查看建筑历史消息
- [x] 6. 查看路线详细信息功能增强
- [x] 7. 首页消息顺序的调整

- [x] 1. main 页面选择路线数据组功能

欢迎补充

**Comment by GIRVANAL** [comment]
web端：

- [x] 1. 系统管理员界面及其功能
- [x] 2. 批量导出二维码去重(含点位数据组中验证)
- [x] 3. 编辑数据组功能
- [x] 4. 点位、路线编辑(更新功能)(该功能考虑废弃)

后端：

- [x] 1. 代码风格优化
- [x] 2. 接口逻辑优化
- [x] 3. 单元测试覆盖率提高
- [x] 4. jmeter性能测试

**Comment by Veiasai** [comment]
- [x] 1. 《计算机网络——自顶向下方法》
- [x] 2. 《深入理解Java虚拟机》
- [x] 3. 《容器即服务》
- [x] 4. 《Jmeter实战》
- [x] 5. 《鸟叔Linux服务器架设篇》
- [ ] 6. leetcode中级算法
- [x] 7. leetcode随缘题三十个
- [x] 8. 更新博客三篇

来不及写完中级算法了。。只写了一半多点。。
linux也没看（其实是因为电子书有问题，崩了

**Comment by Veiasai** [comment]
额外完成工作：
做了efk日志系统
prometheus  grafana性能监控系统
